# Generated by Django 6.0.2 on 2026-03-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_resume_education_resume_email_resume_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
