# Generated by Django 6.0.2 on 2026-03-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='industry',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('management', 'Management'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('arts_design', 'Arts_Design'), ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('law', 'Law'), ('manufacturing', 'Manufacturing')], max_length=50),
        ),
    ]
